# Generated by Django 3.2.16 on 2024-12-23 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image_comment'),
        ('blog', '0017_auto_20241221_1244'),
    ]

    operations = [
    ]
